name: "build and deploy Speckle functions"

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  publish-automate-function-version:
    env:
      FUNCTION_SCHEMA_FILE_NAME: functionSchema.json
      SPECKLE_AUTOMATE_URL: https://automate.speckle.dev
      MONGO_CONNECT: mongodb+srv://aecuser:aechack2024@opendetailcluster.qgxprtm.mongodb.net/?retryWrites=true&w=majority&appName=OpenDetailCluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 7.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Extract functionInputSchema
        id: extract_schema
        working-directory: "SpeckleAutomateDotnetExample"
        env:
          MONGO_CONNECT: mongodb+srv://aecuser:aechack2024@opendetailcluster.qgxprtm.mongodb.net/?retryWrites=true&w=majority&appName=OpenDetailCluster
        run: |
          echo $MONGO_CONNECT
          dotnet build --environment MONGO_CONNECT="${{ secrets.MONGO_CONNECT }}"
          dotnet run generate-schema ${HOME}/functionSchema.json
          cat ${HOME}/functionSchema.json
      - name: Speckle Automate Function - Build and Publish
        uses: specklesystems/speckle-automate-github-composite-action@0.7.2
        with:
          speckle_function_command: "dotnet SpeckleAutomateDotnetExample.dll"
          speckle_automate_url: ${{ env.SPECKLE_AUTOMATE_URL }}
          speckle_token: ${{ secrets.SPECKLE_FUNCTION_TOKEN }}
          speckle_function_id: ${{ secrets.SPECKLE_FUNCTION_ID }}
          speckle_function_input_schema_file_path: ${{ env.FUNCTION_SCHEMA_FILE_NAME }}
